- name: updating packages on client
  yum: name=* state=latest
  environment: proxy_env

- name: Installing nagios
  yum: name=nagios state=installed
  environment: proxy_env

- name: Installing all nagios plugins 
  yum: name=nagios-plugins-all state=installed
  environment: proxy_env

- name: Installing nrpe on client
  yum: name=nrpe state=installed
  environment: proxy_env

- name: Installing nrpe nagios plugins
  yum: name=nagios-plugins-nrpe state=installed
  environment: proxy_env

- name: updating xinted.conf with nagios-server details
  template: src=xinetd.conf.j2 dest=/etc/xinetd.conf
  notify: restart xinetd

- name: updating nrpe.cfg with nagios-server details
  lineinfile: dest=/etc/nagios/nrpe.cfg line="allowed_hosts=127.0.0.1,{{ nagios_server }}" regexp="allowed_hosts\=127.0.0.1"
  notify: restart nrpe