---
nagios_host: nagios.virtual-labs.ac.in
nagios_user: nagiosadmin
nagios_password: xxxxxxx
nagios_admin_name: 'Nagios Admin'
nagios_admin_email: jayanth@vlabs.ac.in
nagios_cfg_path: /etc/nagios/nagios.cfg
nrpe_cfg_path: /etc/nagios/nrpe.cfg

########################################
## vars used by configure_servers.yml ##
########################################
nagios_hosts:
     pubdns1: { hostname: "ns1-pub.vlabs.ac.in", group: web }
     pubdns2: { hostname: "ns2-pub.vlabs.ac.in", group: basic_services }  
     reverse-proxy: { hostname: "http.vlabs.ac.in", group: basic_services }
     host1 with nrpe: { hostname: "10.4.15.116", group: web }
     host2 with nrpe: { hostname: "10.4.15.117", group: web }
  
hosts_list: ["pubdns1", "pubdns2", "reverse-proxy", "host1 with nrpe", "host2 with nrpe"]
 
nagios_host_groups:
     basic_services:
      - { service: "ssh", command: "check_ssh" }
      - { service: "ping", command: "check_ping!100.0,20%!500.0,60%" }

     web:
      - { service: "ssh", command: "check_ssh" }
      - { service: "http", command: "check_http" }
      - { service: "https", command: "check_tcp!443" }
      - { service: "ping", command: "check_ping!100.0,20%!500.0,60%" }
      - { service: "nrpe checking users", command: "check_nrpe!check_users"}
      - { service: "nrpe checking load", command: "check_nrpe!check_load"}

nagios_commands:
    - {name: 'check_nrpe', command: '$USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$'}

    